CREATE OR REPLACE FUNCTION "Lookup"."GetStringIdForSlug" (slug VARCHAR(500))
RETURNS INTEGER
LANGUAGE PLPGSQL
AS
$$
DECLARE
    id INTEGER := 0;
BEGIN
    SELECT "Id" INTO id FROM "Lookup"."Strings" WHERE "Slug" = slug;
    
    IF id = 0 THEN
        INSERT INTO "Lookup"."Strings"
            ("Slug")
        VALUES
            (slug)
        RETURNING "Id" INTO id;
    END IF;

    RETURN (SELECT id);
END;
$$;