CREATE OR REPLACE PROCEDURE "Identity"."DeleteUser"
(
    id INT
)
LANGUAGE PLPGSQL
AS
$$
DECLARE
    id INT;
BEGIN
    DELETE FROM "Identity"."UserRoles" WHERE "UserId" = id;
    DELETE FROM "Identity"."UserClaims" WHERE "UserId" = id;
    DELETE FROM "Identity"."UserLogins" WHERE "UserId" = id;
    DELETE FROM "Identity"."UserTokens" WHERE "UserId" = id;

    DELETE FROM "Identity"."Users" WHERE "Id" = id;
END;
$$;