CREATE OR REPLACE PROCEDURE "Identity"."UpsertUserClaim"
(
    userId INT,
    claimType TEXT,
    claimValue TEXT
)
LANGUAGE PLPGSQL
AS
$$
DECLARE
BEGIN
    INSERT INTO "Identity"."UserClaims"
        ("UserId", "ClaimType", "ClaimValue")
    VALUES
        (userId, claimType, claimValue)
    ON CONFLICT ("UserId", "ClaimType")
    DO UPDATE
        SET ClaimValue = claimValue
        WHERE UserId = userId AND ClaimType = claimType;

END;
$$;